; main counter   
    banksel REG4
    movlw   0x0
    movwf   REG4
    movlw   0x12
    call    Write
    call    eeprom_pause  
    movlw   0x13
    call    Write
    call    eeprom_pause
    movlw   0x14
    call    Write
    call    eeprom_pause 
    movlw   0x15
    call    Write
    call    eeprom_pause
; btns
    banksel REG4
    movlw   0x01
    movwf   REG4
    movlw   0x22
    call    Write
    call    eeprom_pause
    banksel REG4
    movlw   0x02
    movwf   REG4
    movlw   0x32
    call    Write
    call    eeprom_pause 
    
    banksel REG4
    movlw   0x0A
    movwf   REG4
    movlw   0x23
    call    Write
    call    eeprom_pause
    movlw   0x33
    call    Write
    call    eeprom_pause
    
    banksel REG4
    movlw   0x0
    movwf   REG4
    movlw   0x24
    call    Write
    call    eeprom_pause 
    movlw   0x25
    call    Write
    call    eeprom_pause
    movlw   0x34
    call    Write
    call    eeprom_pause 
    movlw   0x35
    call    Write
    call    eeprom_pause   
loop  
    goto    loop
